name: Build, lint and test

on: workflow_call

permissions:
  contents: read

jobs:
  lint:
    name: Check Code with stable output
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - name: Checkout source code
        uses: actions/checkout@v4
    - name: Install Rust stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Run rustfmt
      run: cargo fmt --verbose --check -- --color always
    - name: Run clippy
      run: cargo clippy --all-features --all-targets --color always -- --deny warnings

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --release --all-features
      - name: cargo test
        run: cargo test --all-features --all-targets --benches
