name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
